### ISSUE TITLE
auro-eslint-config: bikeshed lint rules

### ISSUE THREAD

**Issue by geoffrich** [AlaskaAirlines/eslint-config#5]
## Is your feature request related to a problem? Please describe.
Some of the existing eslint rules result in code that is not pretty to look at (imo) and cause a lot of frustration. The lint rules should not be a burden -- they should enforce the code style we agree on. I've also heard that the existing lint rules can be a burden to new contributors.  I'm not sure where the existing config originated, but we've had new maintainers added since then. We should take the time to make sure we all agree on the linting standards.

Let's [bikeshed](https://en.wikipedia.org/wiki/Law_of_triviality) the existing config in this issue. Are there any lint rules that have been bugging you? Now's your chance! Comment below with lint rules you'd like to remove or configure to be less strict. Feel free to make a case for keeping rules that someone else wants to remove.

The outcome is this issue should be consensus on the code style rules we want to apply to Auro projects. Depending on how this goes, we may need to schedule an in-person meeting to come to agreement.

## Describe the solution you'd like
Update the eslint config in accordance with team decisions.

## Describe alternatives you've considered
n/a

## Additional context
Related: https://github.com/AlaskaAirlines/eslint-config-auro/issues/4

**Comment by geoffrich** [comment]
Here are some rules I've had issues with:

[one-var](https://eslint.org/docs/rules/one-var) requires consecutive variable declarations to be combined. IMO, this usually makes the code look worse and makes it harder for me to parse, especially when the consecutive declarations [are objects](https://github.com/AlaskaAirlines/auro-interruption/blob/75f988d2157912a0d2e0d6c08155e986514b0fa8/src/component-base.js#L194-L204). This has also caused issues for me in combination with the [sort vars](https://eslint.org/docs/rules/sort-vars) rule, which requires consecutive variable declarations to be ordered alphabetically, which [isn't always possible](https://github.com/AlaskaAirlines/auro-flightline/blob/4e7d755759a36b5b8c72babb2e1f7e73cb1b991b/src/auro-flightline.js#L34-L38). I propose **removing** one-var.

[func-style](https://eslint.org/docs/rules/func-style) requires writing functions as `const a = function { }` instead of `function a() { }`. This is primarily personal preference, but I prefer the latter. I propose **removing** this rule or configuring it to enforce declarations instead of expressions.

[no-magic-numbers](https://eslint.org/docs/rules/no-magic-numbers) requires you to name the magic numbers in your code. Usually this a good thing, but sometimes it results in code [like this](https://github.com/AlaskaAirlines/auro-radio/blob/f5d1ae14b9648a9f484866522ede8df870774628/src/auro-radio-group.js#L17-L19). #4 will allow 0 and 1 as magic numbers. I also propose we configure the rule with `{ "ignoreArrayIndexes": true }` so that array indexes are not considered.

[max-statements](https://eslint.org/docs/rules/max-statements) requires functions to have 10 or less statements. This seems too prescriptive and has [been disabled](https://github.com/search?q=org%3AAlaskaAirlines+eslint-disable+max-statements&type=Code) frequently. I propose we **remove** this rule.

**Comment by geoffrich** [comment]
[no-negated-condition](https://eslint.org/docs/rules/no-negated-condition) is also disabled per-file [frequently](https://github.com/search?q=org%3AAlaskaAirlines+eslint-disable+no-negated-condition&type=code). I don't have a strong opinion on this one, but suggest **removing** it unless someone can make a strong case for it. Frequently disabling of a rule is a sign that there's some friction.

**Comment by blackfalcon** [comment]
I am 100% onboard with this discussion. 

The `eslint:recommended` rules are listed here https://eslint.org/docs/rules/

**Comment by blackfalcon** [comment]
I also created this https://github.com/AlaskaAirlines/eslint-config-auro/issues/4

**Comment by blackfalcon** [comment]
In addition, there has been a request, specifically from auroLabs devs to have a way to disable the linter altogether. IMHO that's an easy fix to remove the linter from the pre-commit scenario.

**Comment by geoffrich** [comment]
We should also remove the following [deprecated](https://eslint.org/docs/rules/#deprecated) rules. Some of these have no replacement. Of the ones that have a replacement, we are either already using the replacement or it's included in the recommended config that we're extending. 

- callback-return
- global-require
- handle-callback-err
- id-blacklist
- indent-legacy
- lines-around-directive
- newline-after-var
- newline-before-return
- no-buffer-constructor
- no-catch-shadow
- no-mixed-requires
- no-native-reassign
- no-negated-in-lhs
- no-new-require
- no-path-concat
- no-process-env
- no-process-exit
- no-restricted-modules
- no-spaced-func
- no-sync
- prefer-reflect

There are also two JSDoc rules that are deprecated. They need to be replaced with an eslint-plugin, so I've created a separate feature https://github.com/AlaskaAirlines/eslint-config-auro/issues/6.

**Comment by blackfalcon** [comment]
I am including @tsalright in this conversation. As far as I know, there is no floor opinion in linting rules and this may be a great opportunity for all of us to get on the same page.

**Comment by tsalright** [comment]
Yes, we do not have a floor wide ruleset. I am so glad this discussion was started! Thanks @geoffrich!! You have already captured the ones I would argue for. `sort-vars` frustrated me and I turned it off in auro-checkbox. `no-magic-numbers` also frustrated me and I ended up turning them off in several components as well.

**Comment by blackfalcon** [comment]
`"one-var": "error",` is gone, what are thoughts on `"one-var-declaration-per-line": "error",`

**Comment by blackfalcon** [comment]
> [no-negated-condition](https://eslint.org/docs/rules/no-negated-condition) is also disabled per-file [frequently](https://github.com/search?q=org%3AAlaskaAirlines+eslint-disable+no-negated-condition&type=code). I don't have a strong opinion on this one, but suggest **removing** it unless someone can make a strong case for it. Frequently disabling of a rule is a sign that there's some friction.

I can see the reasoning behind this as negative logic can be confusing when done wrong. But I agree, when done right it makes sense.

**Comment by jason-capsule42** [comment]
> [one-var](https://eslint.org/docs/rules/one-var) requires consecutive variable declarations to be combined. IMO, this usually makes the code look worse and makes it harder for me to parse, especially when the consecutive declarations [are objects](https://github.com/AlaskaAirlines/auro-interruption/blob/75f988d2157912a0d2e0d6c08155e986514b0fa8/src/component-base.js#L194-L204). This has also caused issues for me in combination with the [sort vars](https://eslint.org/docs/rules/sort-vars) rule, which requires consecutive variable declarations to be ordered alphabetically, which [isn't always possible](https://github.com/AlaskaAirlines/auro-flightline/blob/4e7d755759a36b5b8c72babb2e1f7e73cb1b991b/src/auro-flightline.js#L34-L38). I propose **removing** one-var.

In general, I certainly prefer to not use the one-var rule. Like you @geoffrich, I agree that it's easier to read and understand having them as separate declarations.

I would add though that in the conflict example linked it is technically possible to achieve both the one-var and sorting though I think the solution to meet the eslint requirements is burdensome, makes the code a lot harder to read and provides no measurable benefit that I can tell. I certainly wouldn't want to write the following code...

```
const children = null,
     slot = this.shadowRoot.querySelector('slot);
     
children = slot && slot.assignedNodes().filter((node) => node.nodeName === 'AURO-FLIGHT-SEGMENT');
```

I'm in support of removing the one-var rule.

**Comment by geoffrich** [comment]
> `"one-var": "error",` is gone, what are thoughts on `"one-var-declaration-per-line": "error",`

I'm okay with removing that too, but don't have a strong preference. I think with one-var gone it should only enforce moving declarations onto separate lines when they are combined.

**Comment by jason-capsule42** [comment]
> [max-statements](https://eslint.org/docs/rules/max-statements) requires functions to have 10 or less statements. This seems too prescriptive and has [been disabled](https://github.com/search?q=org%3AAlaskaAirlines+eslint-disable+max-statements&type=Code) frequently. I propose we **remove** this rule.

I agree it's prescriptive. I will say however that the rule has caused me to reconsider my code at times and look for cleaner, slimmer approaches.

I think a very talented developer probably doesn't need the reminder but it is a helpful nudge to consider if you are really writing efficient code or not.

**Comment by jason-capsule42** [comment]
> In addition, there has been a request, specifically from auroLabs devs to have a way to disable the linter altogether. IMHO that's an easy fix to remove the linter from the pre-commit scenario.

I'm not sure about having zero linting rules but, having a much more slimmed down set of rules in use by default would be good here. For instance with the SASS linter I'm thinking all the rules that enforce _only_ consistency and readability could be removed from the default rules.

We could then lint against a separate set of rules when looking at a given repo for possible inclusion/readiness into the Auro Design System.

**Comment by jason-capsule42** [comment]
> `"one-var": "error",` is gone, what are thoughts on `"one-var-declaration-per-line": "error",`

I very much prefer declarations on separate lines. For instance, this error example on the ESlint doc site is something I would rather not encounter in code:

```javascript
let a,
    b = 0, c;
```

I found this way too easy to misread when reviewing code.

**Comment by geoffrich** [comment]
I also went through the recommended eslint config to find out if we have any duplicate rules, i.e. rules that are declared in both our config and the recommended config. We should remove the following because we are already including them by extending `eslint:recommended`:
- no-dupe-else-if
- no-import-assign
- no-setter-return

Also, we should remove any rules set to `"off"`. As far as I can tell, these are not being set by any of the configs we extend, so there is no need to turn them off.

We should also remove [jsx-quotes](https://eslint.org/docs/rules/jsx-quotes), since we aren't writing JSX.

**Comment by blackfalcon** [comment]
@geoffrich updates completed and pushed.

**Comment by geoffrich** [comment]
Looking good. I'd love to hear from @gusnaughton before we close this out to see if he has anything to add.

**Comment by geoffrich** [comment]
Also, one rule I'd like to enable is [semi](https://eslint.org/docs/rules/semi) to be more consistent with use of semicolons. I'm pro-semicolons at the end of statements, any objections?
